baseURL = 'https://tarsisazevedo.com/'
languageCode = 'pt-br'
title = 'Tarsis Azevedo'
theme = "hugo-coder"
defaultcontentlanguage = "pt-br"

paginate = 20

[params]
  author = "Tarsis Azevedo"
  info = "Programador por diversão e dinheiro. Engenheiro de Dados e de Software na Doximity."
  description = "Data Engineer at Doximity. 15+ YOE as developer, working with Python, Go, Infra and Data."
  keywords = "blog,developer,personal,data engineer,engenharia de dados,programação,python"
  gravatar = "tarsis.azevedo@gmail.com"
  colorScheme = "light"
  faviconSVG = "images/favicon.webp"
  favicon_32 = "images/favicon.png"
  favicon_16 = "images/favicon.png"

[params.goatCounter]
  code = "tarsisazevedo"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/tarsisazevedo/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/tarsisazevedo/"
[[params.social]]
  name = "bsky"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://bsky.app/profile/tarsisazevedo.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"